/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  about: () => import("@/views/about/index.vue"),
  configoptions_config: () => import("@/views/configoptions/config/index.vue"),
  configoptions_notice: () => import("@/views/configoptions/notice/index.vue"),
  dashboard: () => import("@/views/dashboard/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "multi-menu_first_child": () => import("@/views/multi-menu/first_child/index.vue"),
  "multi-menu_second_child_home": () => import("@/views/multi-menu/second_child_home/index.vue"),
  "post_post-comment": () => import("@/views/post/post-comment/index.vue"),
  "post_post-forums": () => import("@/views/post/post-forums/index.vue"),
  "post_post-list": () => import("@/views/post/post-list/index.vue"),
  report: () => import("@/views/report/index.vue"),
  role: () => import("@/views/role/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
  user: () => import("@/views/user/index.vue"),
};
